# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: readme.md CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'
    - name: Generate markdown files
      uses: sonofmagic/github-repository-distributor@main
      with:
        token: ${{ secrets.PERSONAL_TOKEN }}
        username: 'sonofmagic'
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.PERSONAL_TOKEN }}
